import { textContent, clip } from './text.js';

/** Plugin-written notes; the handoff injects neither (the body is already there). */
export const HANDOFF_NOTE = 'handoff.md';
export const HANDOFF_LOG = 'handoff-log.md';
export const HANDOFF_PATHS = new Set([HANDOFF_NOTE, HANDOFF_LOG].map(path => `self/notes/${path}`));

const MAX_BODY_CHARS = 200_000;

/** After a committed rotation: overwrite handoff.md with the full, unclipped handoff
 * and append one line to handoff-log.md. Idempotent per window, so a retried call
 * never duplicates a log line.
 * @returns whether anything was written.
 */
export async function recordHandoff(states, session, signal) {
  const state = states.get(session);
  const incoming = state.windows.at(-1);
  const outgoing = state.windows.at(-2);
  if (!outgoing?.summary_item_id) return false;
  const log = state.notes.files.get(`self/notes/${HANDOFF_LOG}`)?.content ?? '';
  if (log.split('\n').some(line => line.startsWith(`- ${incoming.window_id} `))) return false;

  const summarySeq = Number(outgoing.summary_item_id.slice('item_'.length));
  const data = session.eventAt(summarySeq).data;
  // Generated handoffs keep the summarizer's raw output; the window header clipped it.
  const header = textContent(data.summary);
  const generated = outgoing.summary_kind === 'generated'
    && (textContent(data.rawOutput).trim() || /<generated_handoff>\n([\s\S]*)\n<\/generated_handoff>/.exec(header)?.[1]);
  const body = clip(generated || header, MAX_BODY_CHARS);
  const source = generated ? `generated by ${data.provider}/${data.model}` : `${outgoing.summary_kind} record`;
  const time = new Date().toISOString();

  await states.writeNote(session, HANDOFF_NOTE, [
    `# Latest handoff: ${outgoing.window_id} → ${incoming.window_id}`,
    `Written automatically at ${time} when the window rotated (${source}, summary ${outgoing.summary_item_id}). Replaced on every rotation; ${HANDOFF_LOG} lists earlier ones, and history_read_item returns their full text.`,
    '',
    body,
    '',
  ].join('\n'), 'write', signal);
  await states.writeNote(session, HANDOFF_LOG,
    `- ${incoming.window_id} ${time} ${outgoing.summary_item_id} ${source}: ${clip(body.split('\n').find(line => line.trim() && !line.startsWith('#'))?.trim() ?? '', 160)}\n`,
    'append', signal);
  return true;
}
